### ISSUE TITLE
beg for a more beautiful GUI

### ISSUE THREAD

**Issue by jeanns** [kerwin612/PortForwarder#1]
![2024-05-28_111057](https://github.com/kerwin612/PortForwarder/assets/9364502/91eb9fe4-4e57-4399-a6ae-2e720b0cb7ce)
Good job! but the gui can be more beautified?

**Comment by kerwin612** [comment]
What constitutes a more attractive GUI? Could you elaborate on your suggestions or requirements?

**Comment by jeanns** [comment]
> What constitutes a more attractive GUI? Could you elaborate on your suggestions or requirements?

My suggestions are such as :

- [x] 1. Narrow down the title and other headers slightly to highlight the list display;
- [x] 2. Change the icon to a prettier one and display the function of the icon when clicking the mouse on it;
- [x] 3. Enable sorting of fields in the list, such as target address and target port, and so on.

**Comment by kerwin612** [comment]
A [new version](https://github.com/kerwin612/PortForwarder/releases/tag/v0.0.2) has been released based on your suggestions. You can download it for a trial and I'm looking forward to your feedback.

**Comment by jeanns** [comment]
Great job!
The response is so fast that it's incredible
